2023-11-17 16:03:38,342 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f5d7a9a2fd0>: Failed to resolve 'none' ([Errno -3] Temporary failure in name resolution)")': /api/2.0/instance-pools/list
2023-11-17 16:04:05,247 - root - INFO - Processing job: resource/computer/databricks_instance_pool/auto_loader_batch_driver_banking_.json
2023-11-17 16:04:05,249 - urllib3.connectionpool - WARNING - Retrying (Retry(total=5, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f6271ff33d0>: Failed to resolve 'none' ([Errno -3] Temporary failure in name resolution)")': /api/2.0/instance-pools/list
2023-11-17 16:04:07,249 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f6270c9ddd0>: Failed to resolve 'none' ([Errno -3] Temporary failure in name resolution)")': /api/2.0/instance-pools/list
2023-11-17 16:04:11,252 - urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f6270c89e90>: Failed to resolve 'none' ([Errno -3] Temporary failure in name resolution)")': /api/2.0/instance-pools/list
2023-11-17 16:04:19,254 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f6270c9ebd0>: Failed to resolve 'none' ([Errno -3] Temporary failure in name resolution)")': /api/2.0/instance-pools/list
